development:
  adapter: mysql2
  encoding: utf8
  database: ad_pro_development
  username: root
  password: 
  host: 127.0.0.1
  port: 3306
  flags:
    - -COMPRESS
    - FOUND_ROWS
    - MULTI_STATEMENTS
  secure_auth: false

test:
  adapter: mysql2
  encoding: utf8
  database: ad_pro_test
  username: root
  password: 
  host: 127.0.0.1
  port: 3306
  flags:
    - -COMPRESS
    - FOUND_ROWS
    - MULTI_STATEMENTS
  secure_auth: false

production:
test:
  adapter: mysql2
  encoding: utf8
  database: ad_pro_test
  username: root
  password: 
  host: 127.0.0.1
  port: 3306
  flags:
    - -COMPRESS
    - FOUND_ROWS
    - MULTI_STATEMENTS
  secure_auth: false
